name: Run CI

on:
  push:
    # branches:
    #   - "main"
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Validate Locale
      uses: Zandario/locale-checker-action@34556c36c002dc9d6e8d7e002e1c6fdd0be77c64
