name: Run CI

on:
  push:
    # branches:
    #   - "main"
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Validate Locale
      uses: Zandario/locale-checker-action@b90ca8e833b534e266fb0a4ee52c6fb772d96250
